server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8


spring:
  mustache:
    expose-session-attributes: true
  datasource:
      url: jdbc:mariadb://localhost:3306/greendb 
      driver-class-name: org.mariadb.jdbc.Driver
      username: green
      password: green1234


  output:
    ansi:
      enabled: always


